#!/bin/sh

# The below is required as this is included as a /etc/init.d script
# Without the below we get 'missing LSB tags and overrides' warnings
### BEGIN INIT INFO
# Provides:          hhvm-start
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts a HHVM instance
# Description:       Starts a HHVM FastCGI instance via a sock
### END INIT INFO

hhvm --mode daemon -vServer.Type=fastcgi -vServer.FileSocket=/var/run/hhvm/sock
