---
# python may need to be installed manually.
- hosts: all
  vars_files:
    - ../private/vars.yml
  roles:
    - base
    - dsh

- hosts: adminbotservers
  vars_files:
    - ../private/vars.yml
  roles:
    - adminbot

- hosts: mediawikiservers
  vars_files:
    - ../private/vars.yml
  roles:
    - php
    - hhvm
    - mediawiki
    - nginx

- hosts: dbservers
  vars_files:
    - ../private/vars.yml
  roles:
    - mariadb

- hosts: monitoringservers
  vars_files:
    - ../private/vars.yml
  roles:
    - nagios

- hosts: staticservers
  vars_files:
    - ../private/vars.yml
  roles:
    - nfs-server
    
- hosts: mailservers
  vars_files:
    - ../private/vars.yml
  roles:
    - mail

- hosts: redisservers
  vars_files:
    - ../private/vars.yml
  roles:
    - redis

- hosts: dnsservers
  vars_files:
    - ../private/vars.yml
  roles:
    - dns

- hosts: gangliaservers
  vars_files:
    - ../private/vars.yml
  roles:
    - ganglia

- hosts: elasticsearchservers
  vars_files:
    - ../private/vars.yml
  roles:
    - elasticsearch

- hosts: loadbalancerservers
  vars_files:
    - ../private/vars.yml
  roles:
    - loadbalancer

- hosts: apacheservers
  vars_files:
    - ../private/vars.yml
  roles:
    - apache2
    - php
    - hhvm
