#!/bin/bash
#Runs all of the parts of ansible that are needed
#TODO enable a --force option!

# Get options
branch='master'
skiptags=''
while test $# -gt 0; do
        case "$1" in
                --help)
                        echo "options:"
                        echo "--help                show brief help"
                        echo "--branch=BRANCH       specify a branch to use"
                        echo "--skip-tags=TAGS      specify any tags to skip"
                        exit 0
                        ;;
                --branch*)
                        branch=`echo $1 | sed -e 's/^[^=]*=//g'`
                        shift
                        ;;
                --skip-tags*)
                        skiptags=`echo $1 | sed -e 's/^[^=]*=//g'`
                        skiptags="--skip-tags=$skiptags"
                        shift
                        ;;
                *)
                        break
                        ;;
        esac
done

echo "Pulling from $branch"

set -x

# Pull the playbook
/root/ans-pull --branch="$branch"

# Run the playbook
/root/ans-run "$skiptags"

# If the last command was successful then touch the file used by nagios
# It doesn't matter if this was the pull or the run!
if [[ $? == 0 ]]; then
   echo "Touching .ansible.timestamp" && touch /.ansible.timestamp && chmod 775 /.ansible.timestamp
fi
