#!/bin/bash
#Runs the ansible update

# Get options
skiptags=''
while test $# -gt 0; do
        case "$1" in
                --help)
                        echo "options:"
                        echo "--help                show brief help"
                        echo "--skip-tags=TAGS      specify any tags to skip"
                        exit 0
                        ;;
                --skip-tags*)
                        skiptags=`echo $1 | sed -e 's/^[^=]*=//g'`
                        skiptags="--skip-tags $skiptags"
                        shift
                        ;;
                *)
                        break
                        ;;
        esac
done

HOST=$(hostname)

case $HOST in
  (prod12.orain.org) limit="prod12";;
  (prod11.orain.org) limit="prod11";;
  (prod10.orain.org) limit="prod10";;
  (prod9.orain.org) limit="prod9";;
  (prod8.orain.org) limit="prod8";;
  (prod7.orain.org) limit="prod7";;
  (prod6.orain.org) limit="prod6";;
  (prod5.orain.org) limit="prod5";;
  (*)   echo Failed to match host using $HOST && exit 1;;
esac

set -x

echo "Updating $limit from ansible-playbook: $skiptags"
ansible-playbook -c local --limit $limit /root/ansible-playbook/local.yml -i "/root/ansible-playbook/production" $skiptags
