#!/bin/sh
#Runs all of the parts of ansible that are needed
#Also touches our files that is used by nagios

/root/ans-pull && /root/ans-run && echo "Touching .ansible.timestamp" && touch /.ansible.timestamp && chmod 775 /.ansible.timestamp
