#!/bin/bash
#Runs all of the parts of ansible that are needed
#TODO enable a --force option!

# Select the branch
if [ -z "$1" ]; then
   branch="master"
else
   branch=$1
fi

# Pull the playbook
pullout=$(/root/ans-pull "$branch")

# If the book has changed run it!
if [[ $pullout == *true* ]]; then
   /root/ans-run
fi

# If the last command was successful then touch the file used by nagios
# It doesn't matter if this was the pull or the run!
if [[ $? == 0 ]]; then
   echo "Touching .ansible.timestamp" && touch /.ansible.timestamp && chmod 775 /.ansible.timestamp
fi
