#!/bin/bash
#Pulls the latest anisble playbook from github

# Get options
branch='master'
while test $# -gt 0; do
        case "$1" in
                --help)
                        echo "options:"
                        echo "--help                show brief help"
                        echo "--branch=BRANCH       specify a branch to use"
                        exit 0
                        ;;
                --branch*)
                        branch=`echo $1 | sed -e 's/^[^=]*=//g'`
                        shift
                        ;;
                *)
                        break
                        ;;
        esac
done

echo "Pulling ansible from github - $branch"

ansible all -i "localhost," -c local -m git -a "name=https://github.com/Orain/ansible-playbook.git dest=/root/ansible-playbook version=$branch"
